### ISSUE TITLE
Text is very small

### ISSUE THREAD

**Issue by windsorschmidt** [jonathancross/pics.jonathancross.com#10]
The interface text underneath tabs appears very small. Combined with anti-aliasing, I find the text blurry and somewhat difficult to read.

Browser: Firefox Developer Edition v.36.0a2 (2015-01-08)
OS: Linux 4.0.6-1-ARCH #1 SMP PREEMPT x86_64 GNU/Linux
Screen Resolution: 1920x1080

Sample of affected text:
![text](https://cloud.githubusercontent.com/assets/1273851/9257044/50faaf8e-41a8-11e5-9bb6-6f832704b9a0.png)

Sample of more legible text (Wikipedia):
![text2](https://cloud.githubusercontent.com/assets/1273851/9257280/8dc779a0-41a9-11e5-8856-f9d68881d1f5.png)

**Comment by jonathancross** [comment]
Thanks for the bug.
Yes, the homepage still needs work (it is static html which, unlike the the perl-generated code, has not been made [responsive](https://en.wikipedia.org/wiki/Responsive_web_design) yet).

**Comment by jonathancross** [comment]
Should now be good now: http://pics.jonathancross.com
Mobile version is _much_ better  ;-)
Please let me know if you see other issues.

Cheers,  -Jonathan
